# Generated by Django 4.1 on 2022-09-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationuser',
            old_name='orgnization',
            new_name='organization',
        ),
    ]
